CYTOFF:
    assay_name: CyTOFF
    mssm_id: 6
    mssm_postfix: _6
    #path to the location where manifests for all projects are stored; this path will be combined with a path for a particular experiment
    manifest_location: E:\MounSinai\Darpa\Programming\submission\data_examples\J_Drive # /mnt/researchsan02a/Projects
    #path to the actual folder with manifests, should be concatenated to manifest location and project path
    manifest_folder: SampleManifests

    #path to the location where rawdata for all projects are stored; this path will be combined with a path for a particular experiment
    rawdata_location: E:\MounSinai\Darpa\Programming\submission\data_examples\Bulk_Drive # /mnt/researchsan02a/Projects
    #path to the actual folder with assay data files, should be concatenated to manifest location and project path
    rawdata_folder: cytoff
    #rawdata file to be found inside of the folder with raw data for the current sample
    rawdata_summary_file:
        file_path:
        get_data_by: primary_key #possible values: 'primary_key' - retrieve data from row where PK equal sub_aliquot id
        # 'row_num' - retrieve data from a particular row of the file
        row_num:
    #path to the actual folder with assay attachments, should be concatenated to manifest location and project path
    attachement_folder:  cytoff

    #search type for each type of info
    search_manifest: file_content
    search_rawdata_summary: # file_content
        search_by: file_content
        search_deep_level_max: 2 # 0: root folder, 1:first sub-folder, etc.
        exclude_folders:
    read_rawdata_summary_method: file_content
    search_attachment: file_name

    #expected file formats and sheet names (for excel formats only)
    rawdata_summary_file_ext:
        - .xlsx
        - .xls
    rawdata_summary:
        sheet_name: Sample Log
        header_row_number: 1 # 1-based numbering
        pk_column_number: 6 # 1-based numbering

        #start ========= the following currently not in use ===========================
        #comma delimited list identifying names or column numbers based on the value of "sample_id_method"
        pk_fields: 6
        #expected values: "name" or "number"
        pk_method: number
        #sample_id expression, can by a python expression based on specified sample_id_fields; each field has to be presented in figure parentheses
        pk_expression: "{6}"
        #identifies if validation is required for sample_id_expression - expected values: True/False
        pk_eval_required: False
        #end ======================

    attachment_file_ext:
        - fsc

    attach_object: file

SCRNASEQ:
    assay_name: csRNAseq
    mssm_id: 1
    mssm_postfix: _1
    #path to the location where manifests for all projects are stored; this path will be combined with a path for a particular experiment
    manifest_location: E:\MounSinai\Darpa\Programming\submission\data_examples\J_Drive #/mnt/researchsan02a/Projects
    #path to the actual folder with manifests, should be concatenated to manifest location and project path
    manifest_folder: /SampleManifests

    #path to the location where rawdata for all projects are stored; this path will be combined with a path for a particular experiment
    rawdata_location: E:\MounSinai\Darpa\Programming\submission\data_examples\Bulk_Drive #/ext_data/shared
    #path to the actual folder with assay data files, should be concatenated to manifest location and project path
    rawdata_folder: /scrna-seq
    #rawdata file to be found inside of the folder with raw data for the current sample
    rawdata_summary_file:
        file_path: /outs/metrics_summary.csv
        get_data_by: row_num #possible values: 'primary_key' - retrieve data from row where PK equal sub_aliquot id
                                        # 'row_num' - retrieve data from a particular row of the file
        row_num: 2
    #path to the actual folder with assay attachments, should be concatenated to manifest location and project path
    attachement_folder: /scrna-seq/FASTQs

    attach_object: folder

    rawdata_summary_file_ext:
    rawdata_summary_sheet_name:
    attachment_file_ext:

    #search type for each type of info
    search_manifest: file_content
    search_rawdata_summary:
        search_by: folder_name
        search_deep_level_max: 0 # 0: root folder, 1:first sub-folder, etc.
        exclude_folders:
            - FASTQs
            - fastqs
    read_rawdata_summary_method: file_content
    search_attachment: folder_name

SCATACSEQ:
    assay_name: csATACseq
    mssm_id: 2
    mssm_postfix: _2
    #path to the location where manifests for all projects are stored; this path will be combined with a path for a particular experiment
    manifest_location: E:\MounSinai\Darpa\Programming\submission\data_examples\J_Drive #/mnt/researchsan02a/Projects
    #path to the actual folder with manifests, should be concatenated to manifest location and project path
    manifest_folder: /SampleManifests

    #path to the location where rawdata for all projects are stored; this path will be combined with a path for a particular experiment
    rawdata_location: E:\MounSinai\Darpa\Programming\submission\data_examples\Bulk_Drive #/ext_data/shared
    #path to the actual folder with assay data files, should be concatenated to manifest location and project path
    rawdata_folder: /scatac-seq
    #rawdata file to be found inside of the folder with raw data for the current sample
    rawdata_summary_file:
        file_path: /outs/summary.csv
        get_data_by: row_num #possible values: 'primary_key' - retrieve data from row where PK equal sub_aliquot id
                             # 'row_num' - retrieve data from a particular row of the file
        row_num: 2
    #path to the actual folder with assay attachments, should be concatenated to manifest location and project path
    attachement_folder: /scrna-seq/FASTQs

    #search type for each type of info
    search_manifest: file_content
    search_rawdata_summary:
        search_by: folder_name
        search_deep_level_max: 0 # 0: root folder, 1:first sub-folder, etc.
        exclude_folders:
            - FASTQs
            - fastqs
    read_rawdata_summary_method: file_content
    search_attachment: folder_name

    attach_object: folder




