ASSAYS:
    CYTOF:
        assay_name: CyTOF
        mssm_id: 6
        mssm_postfix: _6
        #path to the location where manifests for all projects are stored; this path will be combined with a path for a particular experiment
        manifest_location: /mnt/researchsan02a/Projects
        #path to the actual folder with manifests, should be concatenated to manifest location and project path
        manifest_folder: /SampleManifests

        #path to the location where rawdata for all projects are stored; this path will be combined with a path for a particular experiment
        rawdata_location: /mnt/researchsan02a/Projects
        #path to the actual folder with assay data files, should be concatenated to manifest location and project path
        rawdata_folder: /AsayData/CyTOF
        #rawdata file to be found inside of the folder with raw data for the current sample
        rawdata_file: /outs/metrics_summary.csv
        #path to the actual folder with assay attachments, should be concatenated to manifest location and project path
        attachement_folder:  /AsayData/CyTOF

        #search type for each type of info
        search_manifest: file_content
        search_rawdata: file_content
        search_attachment: file_name

        #expected file formats
        file_ext_manifest:
            - xlsx
            - xls
            - csv
        file_ext_rawdata:
            - xlsx
        file_ext_attachment:
            - fsc

    SCRNASEQ:
        assay_name: csRNAseq
        mssm_id: 1
        mssm_postfix: _1
        #path to the location where manifests for all projects are stored; this path will be combined with a path for a particular experiment
        manifest_location: /mnt/researchsan02a/Projects
        #path to the actual folder with manifests, should be concatenated to manifest location and project path
        manifest_folder: /SampleManifests

        #path to the location where rawdata for all projects are stored; this path will be combined with a path for a particular experiment
        rawdata_location: /ext_data/shared
        #path to the actual folder with assay data files, should be concatenated to manifest location and project path
        rawdata_folder: /scrna-seq
        #rawdata file to be found inside of the folder with raw data for the current sample
        rawdata_file: /outs/metrics_summary.csv
        #path to the actual folder with assay attachments, should be concatenated to manifest location and project path
        attachement_folder: /scrna-seq/FASTQs

        #search type for each type of info
        search_manifest: file_content
        search_rawdata: folder_name
        search_attachment: folder_name

        #expected file formats
        file_ext_manifest:
            - xlsx
            - xls
            - csv
        file_ext_rawdata:
        file_ext_attachment:

FORMATS:
    MANIFESTS:
        CENTERS:
            HI:
                #comma delimited list identifying names or column numbers based on the value of "sample_id_method"
                sample_id_fields: Barcode
                #expected values: "name" or "number"
                sample_id_method: name
                #sample_id expression, can by a python expression based on specified sample_id_fields; each field has to be presented in figure parentheses
                sample_id_expression: "{Barcode}" #"'-'.join(['{4}','{2}']) ##'{Col4}'"
                #identifies if validation is required for sample_id_expression - expected values: True/False
                sample_id_eval_required: False
    RAWDATA:
        ASSAYS:
            CYTOF:
                #comma delimited list identifying names or column numbers based on the value of "sample_id_method"
                sample_id_fields: Subject ID
                #expected values: "name" or "number"
                sample_id_method: name
                #sample_id expression, can by a python expression based on specified sample_id_fields; each field has to be presented in figure parentheses
                sample_id_expression: "{Subject ID}" #"'-'.join(['{4}','{2}']) ##'{Col4}'"
                #identifies if validation is required for sample_id_expression - expected values: True/False
                sample_id_eval_required: False



