CENTERS:
    DEFAULT:
        #comma delimited list identifying names or column numbers based on the value of "sample_id_method"
        sample_id_fields: Barcode
        #expected values: "name" or "number"
        sample_id_method: name
        #sample_id expression, can by a python expression based on specified sample_id_fields; each field has to be presented in figure parentheses
        sample_id_expression: "{Barcode}"
        #identifies if validation is required for sample_id_expression - expected values: True/False
        sample_id_eval_required: False

        #expected file formats and sheet names (for excel formats only)
        manifest_file_ext_:
            - xlsx
            - xls
        manifest_sheet_name: Sheet1

    HI:
        #comma delimited list identifying names or column numbers based on the value of "sample_id_method"
        sample_id_fields: Barcode
        #expected values: "name" or "number"
        sample_id_method: name
        #sample_id expression, can by a python expression based on specified sample_id_fields; each field has to be presented in figure parentheses
        sample_id_expression: "{Barcode}"
        #identifies if validation is required for sample_id_expression - expected values: True/False
        sample_id_eval_required: False

        #expected file formats and sheet names (for excel formats only)
        manifest_file_ext_:
            - xlsx
            - xls
        manifest_sheet_name: Sheet1




