SCRNA_SEQ:
    assay_name: csRNAseq
    mssm_id: 1
    mssm_postfix: _1

    data_sources:
        - rawdata
        - attachment

    rawdata:
        #path to the location where data_retrieval for all projects are stored; this path
        #will be combined with a path for a particular experiment
        location: D:\MounSinai\Darpa\Programming\submission\data_examples\Bulk_Drive\ECHO
        #path to the actual folder with assay data files, should be concatenated to manifest location and project path
        sub_folder: /scrna-seq

        search_method: # search_rawdata_summary
            search_by: folder_name #possible options: file_content, folder_name
            search_deep_level_max: 0 # 0: root folder, 1:first sub-folder, etc.
            exclude_folders:
                - FASTQs
                - fastqs
            file_ext: # rawdata_summary_file_ext:  #must include dot (.) in-front of an extension
            single_file_path: /outs/metrics_summary.csv

        file_content_details:
            get_data_by: row_num #possible values: 'primary_key' - retrieve data from row where PK equal aliquot id
                                     # 'row_num' - retrieve data from a particular row of the file
            get_by_row_num: # 'row_num' - retrieve data from a particular row of the file
                row_num: 2
            get_by_primary_key:
                header_row_number: # 1-based numbering
                pk_column_number: # 1-based numbering
            excel:
                sheet_name:

    attachment:
        location: D:\MounSinai\Darpa\Programming\submission\data_examples\Bulk_Drive\ECHO
        #path to the actual folder with assay rawdata_attachments, should be concatenated to manifest location and project path
        attachment_folder:
            -
                folder: /scrna-seq/FASTQs
                tar_dir: fastqs
                # If set to True, it will include parent folder preceding the aliquot attachment to the tar file
                # tar_include_parent_dir: True
                validate_tar_content: True
            -
                folder: /scrna-seq
                tar_dir: processed
                # validate_tar_content: False
        attachment_search_by: folder_name #possible options: file_name and folder_name
        search_deep_level_max: 0 # 0: root folder, 1:first sub-folder, etc.
        exclude_folders:
        attach_object: folder #possible options: folder and file
        attachment_file_ext: #must include dot (.) in-front of an extension

SCATAC_SEQ:
    assay_name: csATACseq
    mssm_id: 2
    mssm_postfix: _2

    data_sources:
        - rawdata
        - attachment

    rawdata:
        #path to the location where data_retrieval for all projects are stored; this path
        #will be combined with a path for a particular experiment
        location: D:\MounSinai\Darpa\Programming\submission\data_examples\Bulk_Drive\ECHO
        #path to the actual folder with assay data files, should be concatenated to manifest location and project path
        sub_folder: /scatac-seq

        search_method: # search_rawdata_summary
            search_by: folder_name #possible options: file_content, folder_name
            search_deep_level_max: 0 # 0: root folder, 1:first sub-folder, etc.
            exclude_folders:
                - FASTQs
                - fastqs
            file_ext: # rawdata_summary_file_ext:  #must include dot (.) in-front of an extension
            single_file_path: /outs/summary.csv

        file_content_details:
            get_data_by: row_num #possible values: 'primary_key' - retrieve data from row where PK equal aliquot id
                                     # 'row_num' - retrieve data from a particular row of the file
            get_by_row_num: # 'row_num' - retrieve data from a particular row of the file
                row_num: 2
            get_by_primary_key:
                header_row_number: # 1-based numbering
                pk_column_number: # 1-based numbering
            excel:
                sheet_name:

    attachment:
        location: D:\MounSinai\Darpa\Programming\submission\data_examples\Bulk_Drive\ECHO
        #path to the actual folder with assay rawdata_attachments, should be concatenated to manifest location and project path
        attachment_folder:
            -
                folder: /scatac-seq/fastqs
                tar_dir: fastq
            -
                folder: /scatac-seq
                tar_dir: processed
        attachment_search_by: folder_name #possible options: file_name and folder_name
        search_deep_level_max: 0 # 0: root folder, 1:first sub-folder, etc.
        exclude_folders:
        attach_object: folder #possible options: folder and file
        attachment_file_ext: #must include dot (.) in-front of an extension

CYTOF:
    assay_name: CyTOF
    mssm_id: 6
    mssm_postfix: _6

    data_sources:
        # - rawdata
        - assaydata
        - attachment

    assaydata:
        #path to the location where data_retrieval for all projects are stored; this path
        #will be combined with a path for a particular experiment
        location: D:\MounSinai\Darpa\Programming\submission\data_examples\J_Drive\ECHO\SampleInfo
        #path to the actual folder with assay data files, should be concatenated to manifest location and project path
        sub_folder: /AssayData/cytof/DataQC

        search_method: # search_rawdata_summary
            search_by: file_content #possible options: file_content, folder_name
            search_deep_level_max: 1 # 0: root folder, 1:first sub-folder, etc.
            exclude_folders:

            file_ext: # rawdata_summary_file_ext:  #must include dot (.) in-front of an extension
                - .xlsx
                #- .xls
                - .csv
            single_file_path:

        file_content_details:
            get_data_by: primary_key #possible values: 'primary_key' - retrieve data from row where PK equal aliquot id
                                     # 'row_num' - retrieve data from a particular row of the file
            get_by_row_num:
                # 'row_num' - retrieve data from a particular row of the file
                row_num:
            get_by_primary_key:
                header_row_number: 7 # 1-based numbering
                pk_column_number: 1 # 1-based numbering
            excel:
                sheet_name:

    attachment:
        location: D:\MounSinai\Darpa\Programming\submission\data_examples\J_Drive\ECHO\SampleInfo # D:\MounSinai\Darpa\Programming\submission\data_examples\Bulk_Drive
        #path to the actual folder with assay rawdata_attachments, should be concatenated to manifest location and project path
        attachment_folder:
            -
                folder: /AssayData/cytof/rawdata
                tar_dir: fcs
                tar_include_parent_dir: True
                validate_tar_content: True

        attachment_search_by: file_name #possible options: file_name and folder_name
        search_deep_level_max: 2 # 0: root folder, 1:first sub-folder, etc.
        exclude_folders:
        attach_object: file #possible options: folder and file
        attachment_file_ext: #must include dot (.) in-front of an extension
            - .fcs

EPIC:
    assay_name: epic
    mssm_id: 5
    mssm_postfix: _5

    data_sources:
        # - rawdata
        # - assaydata
        - attachment

    assaydata:
        #path to the location where data_retrieval for all projects are stored; this path
        #will be combined with a path for a particular experiment
        location: D:\MounSinai\Darpa\Programming\submission\data_examples\J_Drive\ECHO\SampleInfo
        #path to the actual folder with assay data files, should be concatenated to manifest location and project path
        sub_folder: /AssayData/Methylome/DataQC

        search_method: # search_rawdata_summary
            search_by: file_content #possible options: file_content, folder_name
            search_deep_level_max: 1 # 0: root folder, 1:first sub-folder, etc.
            exclude_folders:

            file_ext: # rawdata_summary_file_ext:  #must include dot (.) in-front of an extension
                - .xlsx
                - .xls
                # - .csv
            single_file_path:

        file_content_details:
            get_data_by: primary_key #possible values: 'primary_key' - retrieve data from row where PK equal aliquot id
                                     # 'row_num' - retrieve data from a particular row of the file
            get_by_row_num:
                # 'row_num' - retrieve data from a particular row of the file
                row_num:
            get_by_primary_key:
                header_row_number: 1 # 1-based numbering
                pk_column_number: 1 # 1-based numbering
            excel:
                sheet_name:

    attachment:
        location: D:\MounSinai\Darpa\Programming\submission\data_examples\Bulk_Drive\ECHO
        # path to the actual folder with assay rawdata_attachments, should be concatenated to manifest location and project path
        attachment_folder:
            -
                folder: /methylome
                tar_dir: epic
                tar_include_parent_dir: False
                validate_tar_content: True

        attachment_search_by: folder_name #possible options: file_name and folder_name
        search_deep_level_max: 1 # 0: root folder, 1:first sub-folder, etc.
        exclude_folders:
        attach_object: folder #possible options: folder and file
        attachment_file_ext: #must include dot (.) in-front of an extension

RNASEQ:
    assay_name: RNASEQ
    mssm_id: 3
    mssm_postfix: _3

    data_sources:
        - assaydata
        #- attachment

    assaydata:
        #path to the location where data_retrieval for all projects are stored; this path
        #will be combined with a path for a particular experiment
        location: D:\MounSinai\Darpa\Programming\submission\data_examples\J_Drive\ECHO\SampleInfo
        #path to the actual folder with assay data files, should be concatenated to manifest location and project path
        sub_folder: /AssayData/RNAseq/DataQC

        search_method: # search_rawdata_summary
            search_by: file_content #possible options: file_content, folder_name
            search_deep_level_max: 1 # 0: root folder, 1:first sub-folder, etc.
            exclude_folders:

            file_ext: # rawdata_summary_file_ext:  #must include dot (.) in-front of an extension
                - .xlsx
                - .xls
            single_file_path:

        file_content_details:
            get_data_by: primary_key #possible values: 'primary_key' - retrieve data from row where PK equal aliquot id
                                     # 'row_num' - retrieve data from a particular row of the file
            get_by_row_num:
                # 'row_num' - retrieve data from a particular row of the file
                row_num:
            get_by_primary_key:
                header_row_number: 4 # 1-based numbering
                pk_column_number: 3 # 1-based numbering
            excel:
                sheet_name:

    attachment:
        location: D:\MounSinai\Darpa\Programming\submission\data_examples\Bulk_Drive\ECHO
        #path to the actual folder with assay rawdata_attachments, should be concatenated to manifest location and project path
        attachment_folder:
            -
                folder: /rnaseq
                tar_dir:

        attachment_search_by: file_name #possible options: file_name and folder_name
        search_deep_level_max: 2 # 0: root folder, 1:first sub-folder, etc.
        exclude_folders:
        attach_object: file #possible options: folder and file
        attachment_file_ext: #must include dot (.) in-front of an extension
            - .fcs





