HI:
    data_sources:
        # - rawdata
        # - assaydata
        - metadata_db

    assaydata:
        #path to the location where data_retrieval for all projects are stored; this path
        #will be combined with a path for a particular experiment
        location: D:\MounSinai\Darpa\Programming\submission\data_examples\J_Drive\ECHO\SampleInfo
        #path to the actual folder with assay data files, should be concatenated to manifest location and project path
        sub_folder: /AssayData/cytof/DataQC

        search_method: # search_rawdata_summary
            search_by: file_content #possible options: file_content, folder_name
            search_deep_level_max: 1 # 0: root folder, 1:first sub-folder, etc.
            exclude_folders:

            file_ext: # rawdata_summary_file_ext:  #must include dot (.) in-front of an extension
                - .xlsx
                #- .xls
                - .csv
            single_file_path:

        file_content_details:
            get_data_by: primary_key #possible values: 'primary_key' - retrieve data from row where PK equal aliquot id
            # 'row_num' - retrieve data from a particular row of the file
            get_by_row_num:
                # 'row_num' - retrieve data from a particular row of the file
                row_num:
            get_by_primary_key:
                header_row_number: 7 # 1-based numbering
                pk_column_number: 1 # 1-based numbering
            excel:
                sheet_name:

    metadata_db:
        mdb_study_id: 7
        db_config_section_name: MDB




