#dictionary etnries for assays (naming conversions)
assay:
    # expected values: "rna_seq", "scrna_seq", "atac_seq", "chip_seq", "scatac_seq", "medip_seq", "mint_chip", "wgbs",
    # "snatac_seq", "snmc_seq", "cytof", "epic"
    rnaseq: rna_seq
    rna-seq: rna_seq
    rna_seq: rna_seq
    scrnaseq: scrna_seq
    scrna-seq: scrna_seq
    scrna_seq: scrna_seq
    atacseq: atac_seq
    atac-seq: atac_seq
    atac_seq: atac_seq
    scatacseq: scatac_seq
    scatac-seq: scatac_seq
    scatac_seq: scatac_seq
    cytof: cytof
    methylation: epic
    epic: epic
    methylome: epic
    "methylation_epic": epic

assay_sub_aliquot_postfix:
    scrna_seq: _1
    scatac_seq: _2
    rna_seq: _3
    atac_seq: _4
    epic: _5
    cytof: _6

metadata:
    pro_or_ret:
        retrospective1: Retrospective
        prospective: Prospective
        _not_defined: Not Defined
    condition:
        infected: I
        i: I
        control: C
        c: C
    exposure_code:
        hiv: HIV
        mrsa: MRSA
        mssa: MSSA
        denv: DENV
        anth: ANTH
        zika: ZIKA
    sample_type:
        pbmc: PBMC
        plasma: Plasma
    sex:
        m: M
        male: M
        f: F
        Female: F
        _not_defined: other