#dictionary etnries for assays (naming conversions)
assay:
    # expected values: "rna_seq", "scrna_seq", "atac_seq", "chip_seq", "scatac_seq", "medip_seq", "mint_chip", "wgbs",
    # "snatac_seq", "snmc_seq", "cytof", "epic"
    rnaseq: rna_seq
    rna-seq: rna_seq
    rna_seq: rna_seq
    scrnaseq: scrna_seq
    scrna-seq: scrna_seq
    scrna_seq: scrna_seq
    atacseq: atac_seq
    atac-seq: atac_seq
    atac_seq: atac_seq
    scatacseq: scatac_seq
    scatac-seq: scatac_seq
    scatac_seq: scatac_seq
    cytof: cytof
    methylation: epic
    epic: epic
    methylome: epic
    "methylation_epic": epic
    multiome: multiome
    scmultiome: multiome

assay_sub_aliquot_postfix:
    scrna_seq: [_1]
    scatac_seq: [_2,_7]
    rna_seq: [_3]
    atac_seq: [_4]
    epic: [_5]
    cytof: [_6]
    multiome: [_7]
