#dictionary etnries for assays (naming conversions)
assay:
    # expected values: "rna_seq", "scrna_seq", "atac_seq", "chip_seq", "scatac_seq", "medip_seq", "mint_chip", "wgbs",
    # "snatac_seq", "snmc_seq", "cytof", "epic"
    rnaseq: rna_seq
    rna-seq: rna_seq
    rna_seq: rna_seq
    scrnaseq: scrna_seq
    scrna-seq: scrna_seq
    scrna_seq: scrna_seq
    atacseq: atac_seq
    atac-seq: atac_seq
    atac_seq: atac_seq
    scatacseq: scatac_seq
    scatac-seq: scatac_seq
    scatac_seq: scatac_seq
    cytof: cytof
    methylation: epic
    epic: epic
    methylome: epic
    "methylation_epic": epic

assay_sub_aliquot_postfix:
    scrna_seq: _1
    scatac_seq: _2
    rna_seq: _3
    atac_seq: _4
    epic: _5
    cytof: _6

metadata:
    sample_type:
        pbmc: PBMC
        plasma: Plasma
        whole blood: Whole Blood
        dna: DNA
        rna: RNA
    pro_or_ret:
        retrospective: Retrospective
        prospective: Prospective
        _not_defined: Not Defined
    exposure_code:
        hiv: HIV
        mrsa: MRSA
        mssa: MSSA
        denv: DENV
        anth: ANTH
        zika: ZIKA
        op: OP
    condition_code:
        infected: I
        i: I
        control: C
        c: C
        e: E
        l: L
        v: V
        w: W
        m: M
        u: U
        h: H
    sex:
        m: M
        male: M
        f: F
        Female: F
        _not_defined: other
    yes_no-T_F:
        yes: T
        y: T
        no: F
        n: F
        true: T
        t: T
        false: F
        f: F
