#release_v1.1

DB: # this section currently not in use

    #dev conn string: Driver={SQL Server};Server=localhost\sqlexpress;Database=dw_motrpac;User=mt_internal_user;Password=se@lf0n1nt3rn@l
    #prod conn string: Driver={SQL Server};Server=10.160.20.65\SSQL_2016;Database=dw_motrpac;User=mt_internal_user;Password=se@lf0n1nt3rn@l
    #DB connection string
    mdb_conn_str: Driver={SQL Server};Server=localhost\sqlexpress;Database=dw_motrpac;User=mt_internal_user;Password=se@lf0n1nt3rn@l
    # name of the stored proc to be used to load samples to DB
    mdb_sql_proc_load_sample: exec usp_load_single_sample @study_id = {study_id}, @sample_id ='{sample_id}', @forms ='{smpl_json}', @dict_json='{dict_json}', @dict_path='{dict_path}', @filepath='{filepath}', @dict_update={dict_update}, @samlpe_update={samlpe_update}

    # name of field templates for updating of stored procedure parameters (specified in "mdb_sql_proc_load_sample")
    fld_tmpl_study_id: '{study_id}'
    fld_tmpl_sample_id: '{sample_id}'
    fld_tmpl_row_json: '{smpl_json}'
    fld_tmpl_dict_json: '{dict_json}'
    fld_tmpl_dict_path: '{dict_path}'
    fld_tmpl_filepath: '{filepath}'
    fld_tmpl_dict_update: '{dict_update}'
    fld_tmpl_samlpe_update: '{samlpe_update}'

Location:
    # path to the folder where new request files are located
    requests: /mnt/researchsan02a/Projects/ECHO/LL_MIT_Submissions/Submissions/Pending # /ext_data/shared/.apps/echo_submission/echo_submission_v1.1/input_output/requests
    # path to the folder where processed request files are located
    requests_processed: /mnt/researchsan02a/Projects/ECHO/LL_MIT_Submissions/Submissions/Processed # /ext_data/shared/.apps/echo_submission/echo_submission_v1.1/input_output/requests/processed_requests
    # path to the folder where request level log files are located (one log file per request)
    request_logs: /ext_data/shared/.apps/echo_submission/echo_submission_v1.1/input_output/request_logs
    # path to the folder where application level log files are located (one per application run)
    app_logs: /ext_data/shared/.apps/echo_submission/echo_submission_v1.1/input_output/process_logs
    # path to the folder where created submission packages will be located. One package sub_folder per request.
    output_packages: /ext_data/shared/.apps/echo_submission/echo_submission_v1.1/input_output/submission_packages

Logging:
    #main log - log created by the main application
    #request log - log created for each processed request

    #defines log levels to be used for "main" and "file" logs. Usual values are INFO and DEBUG
    main_log_level: INFO
    request_log_level: INFO

Email:
    #default settings for sending emails
    smtp_server: smtp.mssm.edu
    smtp_server_port: 25
    default_from_email: stas.rirak@mssm.edu
    sent_to_emails: stasrirak.ms@gmail.com, stasrira@yahoo.com, stas.rirak@mssm.edu
    send_emails: True # expected values: True, False

submission_forms:
    -
        name: assay_collection
        assignment: request # expected values are: "request" and "aliquot"
    #-
    #    name: aliquot_metadata
    #    assignment: aliquot
    -
        name: sequence_item_metadata
        assignment: aliquot # expected values are: "request" and "aliquot"

