#Peerless release_v1.5

DB: # this section currently not in use

    #dev conn string: Driver={SQL Server};Server=localhost\sqlexpress;Database=dw_motrpac;User=mt_internal_user;Password=se@lf0n1nt3rn@l
    #prod conn string: Driver={SQL Server};Server=10.9.10.59\SQLVP201606;Database=dw_motrpac;User=mt_internal_user;Password=se@lf0n1nt3rn@l3rn@l
    #DB connection string
    mdb_conn_str: Driver={SQL Server};Server=10.9.10.59\SQLVP201606;Database=dw_motrpac;User=mt_internal_user;Password=se@lf0n1nt3rn@l
    # name of the stored proc to be used to load samples to DB
    mdb_sql_proc_load_sample: exec usp_load_single_sample @study_id = {study_id}, @sample_id ='{sample_id}', @forms ='{smpl_json}', @dict_json='{dict_json}', @dict_path='{dict_path}', @filepath='{filepath}', @dict_update={dict_update}, @samlpe_update={samlpe_update}

    # name of field templates for updating of stored procedure parameters (specified in "mdb_sql_proc_load_sample")
    fld_tmpl_study_id: '{study_id}'
    fld_tmpl_sample_id: '{sample_id}'
    fld_tmpl_row_json: '{smpl_json}'
    fld_tmpl_dict_json: '{dict_json}'
    fld_tmpl_dict_path: '{dict_path}'
    fld_tmpl_filepath: '{filepath}'
    fld_tmpl_dict_update: '{dict_update}'
    fld_tmpl_samlpe_update: '{samlpe_update}'

Location:
    # path to the folder where new request files are located
    requests: /mnt/researchsan02a/SampleInfo/Peerless/Submissions/Requests
    # path to the folder where processed request files are located
    requests_processed: /mnt/researchsan02a/SampleInfo/Peerless/Submissions/Requests/processed_requests
    # path to the folder where dynamically created request files for disqualified aliquots will be saved
    requests_disqualified: /mnt/researchsan02a/SampleInfo/Peerless/Submissions/Requests/disqualified_for_reprocessing
    # path to the folder where request level log files are located (one log file per request)
    request_logs: /mnt/researchsan02a/SampleInfo/Peerless/Submissions/logs/request_logs
    # path to the folder where application level log files are located (one per application run)
    app_logs: /mnt/researchsan02a/SampleInfo/Peerless/Submissions/logs/process_logs
    # path to the folder where created submission packages will be located. One package sub_folder per request.
    output_packages: /data/stas/peerless_submission/_submission_input_output/submission_packages

    #name of the folder where all logs files will be stored
    #log_folder_name: logs
    #processed_folder_name: processed

DataTransfer:
    #template of the command used for transfer
    # MITLL (direct ssh transfer approach): rsync -v -r --exclude='transfer_*.*' -e ssh $source_dir {!ssh_user!}@txe1-login.mit.edu:$target_dir
    # Peerless (upload using mounted drive approach): rsync -v -r --exclude='transfer_*.*' $source_dir $target_dir
    transfer_command: rsync -v -r --exclude='transfer_*.*' -e ssh $source_dir {!ssh_user!}flash.llnl.gov:$target_dir
    # target directory where to submission package files will be transferred over SSH
    remote_target_dir: /usr/workspace/mba-ihmc/submission_packages
    #ssh user to be used for transferring
    ssh_user: rirak1
    #execute permission for data transfer script, if not set, no permissions will be assigned
    exec_permis: stat.S_IXUSR #this value is to be evaluated by the code

Logging:
    #main log - log created by the main application
    #request log - log created for each processed request

    #defines log levels to be used for "main" and "file" logs. Usual values are INFO and DEBUG
    main_log_level: INFO
    request_log_level: INFO

Email:
    #default settings for sending emails
    smtp_server: smtp.mssm.edu
    smtp_server_port: 25
    default_from_email: stasrirak.ms@gmail.com
    sent_to_emails: stasrirak.ms@gmail.com, stasrira@yahoo.com
    send_emails: True # expected values: True, False

submission_forms:
    -
        name: assay_collection
        assignment: request # expected values are: "request" and "aliquot"
        file_name_id: assay_collection
    #-
    #    name: aliquot_metadata
    #    assignment: aliquot
    -
        name: sequence_item_metadata
        assignment: aliquot # expected values are: "request" and "aliquot"
        file_name_id: sequence

Tar_ball:
    approach: commandline # possible value: 1)"tarfile" - a tarfile module will be use
                      #                 2) commandline - system tar command will be used
    save_md5sum_file: True